from machine import Pin,PWM
from time import sleep_ms
from random import randint

class RGBLED:
    def __init__(self, red:int, green, blue): #arguments are gpio pins
        self.redPart=PWM(Pin(red), 10000)
        self.greenPart=PWM(Pin(green), 10000)
        self.bluePart=PWM(Pin(blue), 10000)
    
    def set_color(self, rValue, gValue, bValue):  #Set final LED color according to passed rgb arguments
        #RGB led is common anode, GPIO pins are current sinks - red(0) is bright red & red (1023) is no red component in color
        self.redPart.duty(1023-rValue)  #Max bits is (2^10 -1) or 1023 for esp32 PWM pin
        self.greenPart.duty(1023-gValue)
        self.bluePart.duty(1023-bValue)

    #Red=0, green=85, blue=170, red=255, transition smoothly between them
    #0 to 255 RGB range
    def rainbow_cycle(self, speed=None):
        scalingFactor=int(1023/85)
        if speed is not None:
            speed=speed 
        else:
            speed=50   #default to 50ms delay if no delay time argument set in function call
        for i in range(255):
            position=i%85
            if i<85:							#transition from bright red to bright blue green smoothly
                rValue=1023-(position*scalingFactor)
                gValue=position*scalingFactor
                bValue=0
            elif i<170:							#transition from bright green to bright blue
                rValue=0
                gValue=1023-(position*scalingFactor)
                bValue=position*scalingFactor
            else:
                rValue=position*scalingFactor   #transition from bight blue to bright red
                gValue=0
                bValue=1023-(position*scalingFactor)
            self.set_color(rValue,gValue,bValue)
            sleep_ms(speed)
    
    #This effect was generated by chatGPT for fun purposes, i try to avoid AI in writing code and used it for an extra light effect only
    def fire_effect(self, speed=30, steps=100):
        """Simulate a flickering fire effect using red/orange/yellow."""
        import math
        from random import randint

        for i in range(steps):
            # Base flicker using sine wave
            flicker = int((math.sin(i / 5) + 1) * 512)  # 0–1024-ish
            
            # Map to RGB for fire colors
            rValue = min(1023, flicker + randint(0, 100))   # mostly red
            gValue = min(1023, flicker // 2 + randint(0, 50))  # some green
            bValue = randint(0, 20)                          # very little blue

            self.set_color(rValue, gValue, bValue)
            sleep_ms(speed)


    


